# Generated by Django 4.2.27 on 2026-01-02 08:14

import BaseAadhar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AadharUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AadharNumber', models.CharField(max_length=14, unique=True)),
                ('FullName', models.CharField(max_length=10)),
                ('PhoneNumber', models.CharField(max_length=10, unique=True)),
                ('Date_Of_Birth', models.DateField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=BaseAadhar.models.upload_to)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
