# Generated by Django 5.0.10 on 2025-05-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AadharUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=15)),
                ('AadharNumber', models.CharField(max_length=16, unique=True)),
                ('Date_Of_Birth', models.DateField()),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
